    env:
        ARM_CLIENT_ID: ${{ secrets.az_client_id }}
        ARM_CLIENT_SECRET: ${{ secrets.az_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.az_subscription_id }}
        ARM_TENANT_ID: ${{ secrets.az_tenant_id }}
